FROM node:14-slim AS BUILDER
WORKDIR /usr/src/app
COPY package.json .
COPY . .
RUN yarn install \
	&& yarn build
# FROM node:12-slim
# WORKDIR /usr/src/app
# COPY --from=BUILDER /usr/src/app/dist /usr/src/app/dist
# COPY --from=BUILDER /usr/src/app/package.json /usr/src/app/
# COPY --from=BUILDER /usr/src/app/yarn.lock /usr/src/app/
# RUN yarn install --frozen-lockfile
CMD ["yarn", "dev"]